### ISSUE TITLE
The player logs are displaying wrong dates

### ISSUE THREAD

**Issue by haloflooder** [Nort721/GodsEye-Issues#240]
A bug report/issue report should contain:

1) GodsEye Build 36 Beta
2) Paper 1.16.1 (134)
3) ProtocolLib 4.6.0-Snapshot-b473
4) Server log: N/A
5) Video/Screenshot: N/A
6) Basically, the player logs show completely wrong dates on them. The server is only a week old (fresh install) and it's showing dates from march/april.

```yaml
  '1':
    Date: 03-010-2020
    Detection: AUTOCLICKER
    Type: TypeI
    TPS: 19.25
    Ping: 21
    PunishType: KICK
    CPS: 7
    reach: 0.0
  '2':
    Date: 03-011-2020
    Detection: SPEED
    Type: TypeD
    TPS: 20.0
    Ping: 18
    PunishType: KICK
  '3':
    Date: 04-058-2020
    Detection: CRITICALS
    Type: TypeA
    TPS: 20.0
    Ping: 13
    PunishType: KICK
    CPS: 2
    reach: 0.0
```

![log image](https://i.imgur.com/2hUfn6y.png)

On a side note:
It would also be nice if it also showed the time of the punishment along with the date. Can easily achieve that by storing the epoch or millis timestamp in the log file and convert it into a date object when reading the log file.
